### ISSUE TITLE
Deadlink in benchmark/tool/C

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Mobile#27]
https://github.com/PaddlePaddle/Mobile/tree/develop/benchmark/tool/C

> Refer to this document to compile the Android version of PaddlePaddle

The link to `this document` is a dead link. What does the `PADDLE_ROOT` mean in the cmake arguments? 

```bash
cmake .. \
-DANDROID_ABI=arm64-v8a \
-DANDROID_STANDALONE_TOOLCHAIN=your/path/to/arm64_standalone_toolchain \
-DPADDLE_ROOT=The output path generated in the first step \
-DCMAKE_BUILD_TYPE=MinSizeRel
```

**Comment by hedaoyuan** [comment]
> What does the PADDLE_ROOT mean in the cmake arguments?

The `PADDLE_ROOT` argument, is the directory that the `CMAKE_INSTALL_PREFIX` argument is set when building paddle.
The `document` link is https://github.com/PaddlePaddle/Paddle/blob/develop/doc/mobile/cross_compiling_for_android_en.md

**Comment by qingqing01** [comment]
Oh, I see... The argument `PADDLE_ROOT` is used in [FindPaddle.cmake](https://github.com/PaddlePaddle/Mobile/blob/develop/benchmark/tool/C/FindPaddle.cmake).
