### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by bushidonggua** [PaddlePaddle/Mobile#3]
错误如下：
    net = mobile_net(image)
  File "mobilenet_pruning.py", line 70, in mobile_net
    stride=1)
  File "mobilenet_pruning.py", line 43, in depthwise_separable
    pa0 = ParamAttr(update_hooks = Hook('dynamic_pruning', sparsity_upper_bound=0.75))
TypeError: __init__() got an unexpected keyword argument 'sparsity_upper_bound'

**Comment by NHZlX** [comment]
dynamic pruning 一直没有merge 到主线中去， 所以可以参照https://github.com/PaddlePaddle/Mobile/tree/master/flowers102/mobilenet_pruning
