### ISSUE TITLE
Investigate Android NN

### ISSUE THREAD

**Issue by abhinavarora** [PaddlePaddle/Mobile#30]
https://developer.android.com/ndk/guides/neuralnetworks/index.html

**Comment by abhinavarora** [comment]
Completed the survey here -> https://github.com/PaddlePaddle/Mobile/wiki/Android-NN-Survey

**Comment by graycreate** [comment]
Has paddlepaddle make use of the Android NNAPI ?

**Comment by Xreki** [comment]
Paddle doesn't make use of Android NNAPI yet, but has plan to support.
