### ISSUE TITLE
Investigate TF Lite

### ISSUE THREAD

**Issue by abhinavarora** [PaddlePaddle/Mobile#31]
https://www.tensorflow.org/mobile/tflite/

**Comment by NHZlX** [comment]
refer: 
https://github.com/PaddlePaddle/Mobile/wiki/Tensorflow-Lite-(Introduction,-motivation-and-few-components-in-depth)
https://github.com/PaddlePaddle/Mobile/wiki/TfLite-Survey

**Comment by kavyasrinet** [comment]
We can move this to Done.

**Comment by kavyasrinet** [comment]
Closing this since we already have the Wiki pages.
