### ISSUE TITLE
The num_filters of depthwise_separable seems wrong in mobilenet

### ISSUE THREAD

**Issue by lhsoft** [PaddlePaddle/Mobile#34]
The  mobile net paper said "We use depthwise convolutions to apply a single filter per each input channel (input depth)".
But in paddlepaddle implementation
```
    tmp = depthwise_separable(tmp,
                              num_filters1=32,
                              num_filters2=64,
                              num_groups=32,
                              stride=1, scale = scale)
```
the num_filters1 is the same as num_groups and the input channel is 32, it will cause a single filter be precessed by 32 filter. so the num_filters1 here should be 1 rather than 32
I‘m glad to fix if possible:)

**Comment by hedaoyuan** [comment]
@NHZlX

**Comment by NHZlX** [comment]
@lhsoft 
```
def depthwise_separable(input, num_filters1, num_filters2, num_groups, stride, scale):
    """
    """
    tmp = conv_bn_layer(
                        input=input,
                        filter_size=3,
                        num_filters=int(num_filters1*scale),
                        stride=stride,
                        padding=1,
                        num_groups=int(num_groups*scale), layer_type='exconv')

    tmp = conv_bn_layer(
                        input=tmp,
                        filter_size=1,
                        num_filters=int(num_filters2*scale),
                        stride=1,
                        padding=0)
    return tmp
```
 the num_filters1 represents the output channel of the depthwise convolution, and the num_filters2 represents the output channel of the pointwise convolution.

**Comment by lhsoft** [comment]
@NHZlX 
Thanks for you reply.
```
    tmp = depthwise_separable(tmp,
                              num_filters1=32,
                              num_filters2=64,
                              num_groups=32,
                              stride=1, scale = scale)
```
And the input channel = 32, so paddle will create 32 * 32 filters.  And each group will process 32/32 = 1 channel by 32 filters, Does it make sense?

**Comment by NHZlX** [comment]
there is something wrong with our doc http://paddlepaddle.org/docs/develop/documentation/zh/api/v2/config/layer.html, we will fix it soon.
