### ISSUE TITLE
mobilenet_pruning这个为什么我跑出来是11M而不是说明中提到的4.3M

### ISSUE THREAD

**Issue by bushidonggua** [PaddlePaddle/Mobile#4]
训练mobilenet_pruning，跟mobilenet那个相比，由12M变为11M，并没有那里面提到的变为4.3M，是为什么呢？

**Comment by NHZlX** [comment]
给我的信息太少了， 把你的配置文件粘贴一下。 训练时候会打印每层的稀疏度的log， 可以把这个粘贴一下

**Comment by bushidonggua** [comment]
是不是一定要用gpu训练才会有效果，每三个pass由于sparsity变大模型会开始逐渐变小一点，我用cpu训练尺寸一直都是11M基本完全没变化，换成用gpu训练好了

**Comment by NHZlX** [comment]
不是的， gpu 和cpu 只是差别在训练速度上。 默认的超参数是end_pass 为60也就是知道end_pass 个pass 后， 才达到提前设定的sparsity。 而interval_pass默认为3 代表，我们每3个pass 会变化一次sparsity， 这两个超参数都是可以改的， 通过`    pa0 = ParamAttr(update_hooks = Hook('dynamic_pruning', sparsity_upper_bound=0.75, interval_pass = 2, end_pass = 20))`  即每两次pass 变化一次sparsity ，直到20个pass后达到0.75的sparsity。

**Comment by bushidonggua** [comment]
可是奇怪的是相同的超参数，训练相同的pass数，我是对比18个pass，gpu训练每3个pass确实会变小，cpu的一直保持11M左右的体积，而我看sparsity确实是不停地在变的，达到0.5以上也没让他有太大的体积变化

**Comment by NHZlX** [comment]
这个确实可能存在问题  你先用gpu训练，稍后我会对cpu的测试一下

**Comment by bushidonggua** [comment]
恩恩，感谢！

**Comment by NHZlX** [comment]
这个bug 已经fix
