### ISSUE TITLE
Refine `models` directory

### ISSUE THREAD

**Issue by hedaoyuan** [PaddlePaddle/Mobile#54]
The `models` directory needs to contain two parts. The first part is some standard model configuration files, such as MobileNet, ResNet, etc., that can be used as benchmark test data. The second part contains some well-trained model parameter files, such as the `mobilenet ssd pascal model`, which can be directly converted to inference model files for deployment to mobile.

**Comment by Xreki** [comment]
I think the structure of the second would be same as https://github.com/PaddlePaddle/models . If we use different data set, there should be a sub-directory.

**Comment by hedaoyuan** [comment]
I moved mobilenet.py and resnet.py to a `configuration` directory, and delete the README.md file, which does not look useful at the moment. I think @NHZlX can refine the `mobilenet_ssd_pascal` directory.

**Comment by NHZlX** [comment]
@Xreki   The sub-directory just offer the model config and parameters? or the instructions for training. If add training process, there must be redundant somehow.

**Comment by Xreki** [comment]
If the training process is the same as that in https://github.com/PaddlePaddle/models , we just provide the config and pre-trained parameters, and write a `README.md` to tell users how to train. Also, we do not need to upload the parameters to github, but give a link to download. We can write a script file to download the parameters (like https://github.com/PaddlePaddle/Mobile/blob/develop/Demo/linux/ssd/models/model_download.sh) and write how to download the parameters in the `README.md`.
