### ISSUE TITLE
建议加上iOS和安卓平台编译好的release库，以便开发者直接下载使用

### ISSUE THREAD

**Issue by realsnake** [PaddlePaddle/Mobile#74]
Hi，
我看文档介绍都是从源码编译出库来再使用，通常是比较费时费力，且提高了使用门槛。 建议加上官方发布的release版本，直接提供下载使用。

**Comment by hedaoyuan** [comment]
这里https://github.com/PaddlePaddle/Mobile/wiki 有一个编译好的库可以使用。

**Comment by realsnake** [comment]
好，多谢
