### ISSUE TITLE
Android demo和iOS demo的对比体验

### ISSUE THREAD

**Issue by afantree** [PaddlePaddle/Mobile#77]
下载了Android分支的demo，编译之后安装之后发现和iOS的不一样，android的相机界面没有识别出来物体

**Comment by Xreki** [comment]
您好，Android分支的demo所使用的模型和iOS是一样的，所以造成识别效果差异的主要原因，应该在于前端的处理。该分支目前还在开发和优化中。另外，如果您有优化的建议，我们会非常欢迎，:smile:

**Comment by afantree** [comment]
谢谢

**Comment by Xreki** [comment]
@afantree 上周五我试用Android分支demo，效果确实存在一些问题。目前已经找到问题并解决啦，欢迎试用~稍后我们会上传下载安装的二维码。
