### ISSUE TITLE
编译Android的PaddlePaddle库最低支持Android API多少

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Mobile#78]
在文档http://www.paddlepaddle.org/docs/develop/documentation/zh/mobile/cross_compiling_for_android_cn.html中提到
>由于arm64架构要求Android API不小于21

如果只是使用到`armeabi-v7a`，最低支持的Android API是多少？

**Comment by Xreki** [comment]
`armeabi-v7a`测试过的最小Android API是`16`。

> 由于arm64架构要求Android API不小于21

另外，这个其实是Android NDK本身的要求。你在Android Studio中可以将API设置成小于`21`，实际上对于`arm64`架构，会默认使用`21`。

**Comment by yeyupiaoling** [comment]
@Xreki 
好的，谢谢~
