### ISSUE TITLE
能否提Android项目的整个项目结构

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Mobile#79]
项目https://github.com/PaddlePaddle/Mobile/tree/develop/Demo/Android/AICamera
这个项目有很多目录都没有，我不知道它的结构是什么，能否把整一个项目目录发我 ，我的邮箱为：yeyupiaoling@foxmail.com

**Comment by Xreki** [comment]
你好，Android Demo应该只有两个目录没有：
1. paddle二进制，可以从[wiki](https://github.com/PaddlePaddle/Mobile/wiki)下载，放到`AICamera/app`目录下。如果你是手动编译的最新版Paddle，`FindPaddle.cmake`可能还有些内容要改动。
2. 模型文件，`AICamera/app/src/main/assets/models`目录下，模型文件可通过https://github.com/PaddlePaddle/Mobile/tree/develop/Demo/Android/AICamera#models 里面的链接下载。

目前缺乏中文文档，操作步骤也没有描述清楚，还请谅解。

**Comment by yeyupiaoling** [comment]
@Xreki 
嗯嗯，收到，我只想在Android的APP上实现简单的图像分类问题，您那个项目有点复杂，注释也比较少，我还在读您的Demo中，我在找以下几个问题：
* 初始化PaddlePaddle
* 加载合并的模型
* 传入图像数据
* 获取预测结果

**Comment by Xreki** [comment]
这个项目确实做了一些特殊的处理：
- 模型要求的图像size，`pascal_mobilenet_300_66.paddle`是300x300x3，`face_mobilenet_160_91.paddle`是160x160x3。摄像头获取到的图像会直接传给c++代码，因此c++代码里面有对图像做resize的功能。另外图像可能需要旋转90、180、270度。

C++代码里面可以一一对应这几个问题：
- 初始化PaddlePaddle

https://github.com/PaddlePaddle/Mobile/blob/477186702e368a55c6a3319f2b78257c7c0ac51d/Demo/Android/AICamera/app/src/main/cpp/paddle_image_recognizer.cpp#L97-L98

- 加载合并的模型

https://github.com/PaddlePaddle/Mobile/blob/477186702e368a55c6a3319f2b78257c7c0ac51d/Demo/Android/AICamera/app/src/main/cpp/paddle_image_recognizer.cpp#L100-L111

- 传入图像数据和获取预测结果，参考以下函数

https://github.com/PaddlePaddle/Mobile/blob/477186702e368a55c6a3319f2b78257c7c0ac51d/Demo/Android/AICamera/app/src/main/cpp/paddle_image_recognizer.cpp#L212-L217

**Comment by yeyupiaoling** [comment]
https://github.com/PaddlePaddle/Mobile/blob/477186702e368a55c6a3319f2b78257c7c0ac51d/Demo/Android/AICamera/app/src/main/cpp/paddle_image_recognizer.cpp#L212-L217

这个函数是如何传入图像数据进行预测的，没看到有图像数据的传入？

**Comment by yeyupiaoling** [comment]
@Xreki 
这个应该是传入数据的关键
https://github.com/PaddlePaddle/Mobile/blob/477186702e368a55c6a3319f2b78257c7c0ac51d/Demo/Android/AICamera/app/src/main/java/com/paddlepaddle/pdcamera/MainActivity.java#L305-L316

但是数据传到这里就不知道怎么没有了
https://github.com/PaddlePaddle/Mobile/blob/477186702e368a55c6a3319f2b78257c7c0ac51d/Demo/Android/AICamera/app/src/main/cpp/paddle_image_recognizer.cpp#L249

看代码应该是这里获取预测结果
https://github.com/PaddlePaddle/Mobile/blob/477186702e368a55c6a3319f2b78257c7c0ac51d/Demo/Android/AICamera/app/src/main/cpp/paddle_image_recognizer.cpp#L251-L267

如果是python的，获取结果是这样的，我指定的是图像分类的，我要实现的也是图像分类的
https://github.com/PaddlePaddle/models/blob/develop/image_classification/infer.py#L73-L77
```python
    probs = paddle.infer(
        output_layer=out, parameters=parameters, input=test_data)
    lab = np.argsort(-probs)
    for file_name, result in zip(file_list, lab):
        print "Label of %s is: %d" % (file_name, result[0])
```

**Comment by yeyupiaoling** [comment]
@Xreki 
我自己使用Android studio创建了一个新项目，打算复原您的dome，在构建的时候出现
![image](https://user-images.githubusercontent.com/26297768/36777574-f263eb2c-1ca4-11e8-8443-b061eb8dbb71.png)

还有这个
![image](https://user-images.githubusercontent.com/26297768/36777609-14ea837c-1ca5-11e8-878e-5353f5dfce8f.png)

**日志文件：**
[CMakeOutput.log](https://github.com/PaddlePaddle/Mobile/files/1766263/CMakeOutput.log)

**Comment by yeyupiaoling** [comment]
@Xreki 
如果我使用创建时，Android studio生成的CMakeList.txt，就不会出错，当然应为我没修改里面的文件，只是修改这而已
```
add_library( # Sets the name of the library.
             paddle_image_recognizer

             # Sets the library as a shared library.
             SHARED

             # Provides a relative path to your source file(s).
             src/main/cpp/image_recognizer_jni.cpp
             src/main/cpp/paddle_image_recognizer.cpp
             src/main/cpp/binary_reader.cpp
             src/main/cpp/image_utils.cpp )
```

我也复制FindPaddle.cmake，还是报错`#include <paddle/capi.h>`，找不到

![image](https://user-images.githubusercontent.com/26297768/36823150-a550c912-1d36-11e8-86d9-3f1a17593a81.png)

**Comment by yeyupiaoling** [comment]
方便问题跟踪和分类，已新建issue，#81
